name: portfolio
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.10
  velocity_x: ^3.3.0
  timelines: ^0.1.0
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: custom
      fonts:
        - asset: assets/Poppins-Regular.ttf
        - asset: assets/Poppins-Light.ttf
          weight: 400
        - asset: assets/Poppins-Medium.ttf
          weight: 600
        - asset: assets/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/Poppins-Bold.ttf
          weight: 800
        - asset: assets/Poppins-Bold.ttf
          weight: 900